project:
  description: Log::Log4perl::Appender::CloudWatch
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm-module: Log::Log4perl::Appender::CloudWatch
min-perl-version: 5.010
dependencies:
  requires: requires
  test-requires: test-requires
path:
  pm-module: lib
  exe-files: bin
  tests: t
extra-files:
  - ChangeLog
  - release-notes.md
  - share:
      - README.md
resources:
  homepage: http://github.com/rlauer6/Log-Log4perl-Appender-CloudWatch.git
  bugtracker:
    web: http://github.com/rlauer6/Log-Log4perl-Appender-CloudWatch/issues
    mailto: rclauer@gmail.com
  repository:
    url: git://github.com/rlauer6/Log-Log4perl-Appender-CloudWatch.git
    web: http://github.com/rlauer6/Log-Log4perl-Appender-CloudWatch.git
    type: 'git'
